export default {
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'DECREMENT_COUNTER',
  ADD_TO_COUNTER: 'ADD_TO_COUNTER',
  ASYNC_SET_COUNTER_START: 'ASYNC_SET_COUNTER_START',
  ASYNC_SET_COUNTER_SUCCESS: 'ASYNC_SET_COUNTER_SUCCESS',
  ASYNC_SET_COUNTER_FAILURE: 'ASYNC_SET_COUNTER_FAILURE',
} as const
