export default {
  INCREMENT_COUNTER: 'STORE_DEFAULT_INCREMENT_COUNTER',
  DECREMENT_COUNTER: 'STORE_DEFAULT_DECREMENT_COUNTER',
  ADD_TO_COUNTER: 'STORE_DEFAULT_ADD_TO_COUNTER',
  ASYNC_SET_COUNTER_START: 'STORE_DEFAULT_ASYNC_SET_COUNTER_START',
  ASYNC_SET_COUNTER_SUCCESS: 'STORE_DEFAULT_ASYNC_SET_COUNTER_SUCCESS',
  ASYNC_SET_COUNTER_FAILURE: 'STORE_DEFAULT_ASYNC_SET_COUNTER_FAILURE',
} as const
